dist: xenial
language: python
sudo: false
os:
  - linux
cache:
  pip: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install codecov
  - pip install .[dev]
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # * E501 - line length limit
  # * E123 - indentation on data structures
  # * W504 - line break after binary operator
  - flake8 . --ignore=F403,E501,E123,E128,W504,W503 --exclude=docs,build
  - py.test --cov=mesa tests/ --cov-report=xml
  - if [ $PYTHON == "3.6" ];
    then black --check --exclude=mesa/cookiecutter-mesa/* .;
    fi
  # - ./tests/test_end_to_end_viz.sh  # needs to be investigated on why this took forever
after_success:
  - codecov